# Generated by Django 4.1.7 on 2023-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-10-27'),
            preserve_default=False,
        ),
    ]
